### ISSUE TITLE
add a way to differ processing of Note and Warning

### ISSUE THREAD

**Issue by Hunam6** [myl7/remark-github-beta-blockquote-admonitions#1]
From what I've understood, right now, if I want to reproduce the behaviour of Github
<img width="229" alt="Screenshot 2023-01-28 at 19 43 21" src="https://user-images.githubusercontent.com/38606542/215282495-427d77ca-633f-4aff-974e-b126932ef440.png">
I cannot because there is not way to process a note and a warning differently.

I can think of two ways:
- either with the ability to assign a different class for each note/warning/...
- or, better IMO, have a new option to do this

**Comment by myl7** [comment]
Items of `classNameMaps` accept a function as the value. The arguments of the function are the title inside `**...**`, and returned value is set as the HTML class. With that, types like note/warning will have different HTML class, so you can process them respectively with CSS query. For example, to set the color:

```js
let config = {
  classNameMaps: {
    block: title => [
      'admonition',
      ...title.toLowerCase().split(/\s+/),
    ],
    title: 'admonition-title',
  },
}
```

```css
.admonition.note > p > strong.admonition-title { color: blue; }
.admonition.warning p > strong.admonition-title { color: yellow; }
```

Icons can also be added with CSS.
